// Advanced challenges (21-30).

export const advanced = [
  {
    id: 'advanced-21', level: 'advanced', db: 'company_db',
    title: 'Subqueries',
    description: 'A query inside a query.',
    objective: 'Use a subquery in WHERE.',
    instructions: 'Find employees who earn more than the average salary of the whole company. Return first_name and salary.',
    example: 'SELECT name FROM products WHERE price > (SELECT AVG(price) FROM products);',
    starter: 'SELECT first_name, salary\nFROM employees\nWHERE salary > \n',
    solution: 'SELECT first_name, salary FROM employees WHERE salary > (SELECT AVG(salary) FROM employees);',
    hints: ['Compute the average inside a subquery in parentheses.', 'Then compare salary to it.', 'WHERE salary > (SELECT AVG(salary) FROM employees);'],
  },
  {
    id: 'advanced-22', level: 'advanced', db: 'company_db',
    title: 'CASE expressions',
    description: 'If/else logic in SQL.',
    objective: 'Use CASE WHEN to classify rows.',
    instructions: 'Return each first_name and salary plus a column salary_band (alias) that is "High" when salary >= 70000 and "Standard" otherwise.',
    example: "SELECT name, CASE WHEN price > 100 THEN 'expensive' ELSE 'cheap' END AS tag FROM products;",
    starter: 'SELECT first_name, salary,\n  CASE\n',
    solution: "SELECT first_name, salary, CASE WHEN salary >= 70000 THEN 'High' ELSE 'Standard' END AS salary_band FROM employees;",
    hints: ['CASE WHEN condition THEN value ELSE other END.', "Use 'High' for salary >= 70000.", "CASE WHEN salary >= 70000 THEN 'High' ELSE 'Standard' END AS salary_band"],
  },
  {
    id: 'advanced-23', level: 'advanced', db: 'company_db',
    title: 'Common Table Expressions (CTE)',
    description: 'Named sub-results with WITH.',
    objective: 'Write a CTE with WITH.',
    instructions: 'Using a CTE named dept_avg that computes each department_id and its average salary (alias avg_salary), return all rows of dept_avg.',
    example: 'WITH totals AS (SELECT category, SUM(price) AS t FROM products GROUP BY category) SELECT * FROM totals;',
    starter: 'WITH dept_avg AS (\n  \n)\nSELECT * FROM dept_avg;',
    solution: 'WITH dept_avg AS (SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id) SELECT * FROM dept_avg;',
    hints: ['The CTE body is a normal SELECT with GROUP BY.', 'Alias the average as avg_salary.', 'WITH dept_avg AS (SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id) SELECT * FROM dept_avg;'],
  },
  {
    id: 'advanced-24', level: 'advanced', db: 'company_db',
    title: 'UNION',
    description: 'Stack results from two queries.',
    objective: 'Combine two result sets with UNION.',
    instructions: 'Return one column named person that contains every employee first_name UNIONed with every department name (no duplicates).',
    example: "SELECT city FROM customers UNION SELECT city FROM employees;",
    starter: "SELECT first_name AS person FROM employees\n\n\n",
    solution: 'SELECT first_name AS person FROM employees UNION SELECT name FROM departments;',
    hints: ['UNION removes duplicates automatically.', 'Both SELECTs must return the same number of columns.', 'SELECT first_name AS person FROM employees UNION SELECT name FROM departments;'],
  },
  {
    id: 'advanced-25', level: 'advanced', db: 'company_db',
    title: 'Complex JOINs',
    description: 'Three-way join with aggregation.',
    objective: 'Join employees → employee_projects → projects.',
    instructions: 'Return each employee first_name (no duplicates) and the number of projects they work on (alias num_projects). Include employees with zero projects.',
    example: 'SELECT c.name, COUNT(o.order_id) FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id GROUP BY c.name;',
    starter: 'SELECT e.first_name, \nFROM employees e\n',
    solution: 'SELECT e.first_name, COUNT(ep.project_id) AS num_projects FROM employees e LEFT JOIN employee_projects ep ON e.employee_id = ep.employee_id GROUP BY e.employee_id, e.first_name;',
    hints: ['LEFT JOIN employee_projects keeps employees without projects.', 'COUNT(ep.project_id) counts only matched rows (0 for no match).', "Group by the employee id and name: GROUP BY e.employee_id, e.first_name;"],
  },
  {
    id: 'advanced-26', level: 'advanced', db: 'company_db',
    title: 'Window functions',
    description: 'Aggregates without collapsing rows.',
    objective: 'Use AVG() OVER (PARTITION BY ...).',
    instructions: 'Return first_name, department_id and salary, plus a column dept_avg_salary: the average salary of the employee\'s department computed with a window function (every row stays).',
    example: 'SELECT name, category, AVG(price) OVER (PARTITION BY category) FROM products;',
    starter: 'SELECT first_name, department_id, salary,\n  \nFROM employees;',
    solution: 'SELECT first_name, department_id, salary, AVG(salary) OVER (PARTITION BY department_id) AS dept_avg_salary FROM employees;',
    hints: ['Window functions use OVER (...).', 'PARTITION BY department_id makes AVG per department.', 'AVG(salary) OVER (PARTITION BY department_id) AS dept_avg_salary'],
  },
  {
    id: 'advanced-27', level: 'advanced', db: 'company_db',
    title: 'Ranking',
    description: 'RANK() and ROW_NUMBER().',
    objective: 'Rank employees by salary.',
    instructions: 'Return first_name, salary and a rank column salary_rank: the salary rank from highest to lowest (ties get the same rank), for all employees.',
    example: 'SELECT name, RANK() OVER (ORDER BY price DESC) FROM products;',
    starter: 'SELECT first_name, salary,\n  \nFROM employees;',
    solution: 'SELECT first_name, salary, RANK() OVER (ORDER BY salary DESC) AS salary_rank FROM employees;',
    hints: ['RANK() OVER (ORDER BY ...) assigns ranks.', 'Order by salary DESC so rank 1 is the highest paid.', 'RANK() OVER (ORDER BY salary DESC) AS salary_rank'],
    ordered: true,
  },
  {
    id: 'advanced-28', level: 'advanced', db: 'company_db',
    title: 'Advanced filtering',
    description: 'IN + correlated subquery.',
    objective: 'Use IN with a subquery.',
    instructions: 'Find the first_name of employees who are assigned to project 1 or project 2 (via employee_projects). Return each name once.',
    example: 'SELECT name FROM customers WHERE customer_id IN (SELECT customer_id FROM orders WHERE status = \'shipped\');',
    starter: 'SELECT first_name\nFROM employees\nWHERE \n',
    solution: 'SELECT DISTINCT first_name FROM employees WHERE employee_id IN (SELECT employee_id FROM employee_projects WHERE project_id IN (1, 2));',
    hints: ['Use IN with a subquery on employee_projects.', 'employee_projects has employee_id and project_id columns.', 'WHERE employee_id IN (SELECT employee_id FROM employee_projects WHERE project_id IN (1, 2)) and add DISTINCT.'],
  },
  {
    id: 'advanced-29', level: 'advanced', db: 'company_db',
    title: 'Data modification',
    description: 'INSERT, UPDATE, DELETE.',
    objective: 'Modify data with DML statements.',
    instructions: 'Do three things in order: (1) INSERT a new department with id 6, name "Legal", location "Remote", budget 200000. (2) UPDATE employees to set department_id = 6 for employee_id 7. (3) SELECT first_name, department_id FROM employees WHERE employee_id = 7 to confirm.',
    example: 'INSERT INTO departments VALUES (6, \'Legal\', \'Remote\', 200000);',
    starter: '-- Run all three statements together\n',
    solution: "INSERT INTO departments VALUES (6, 'Legal', 'Remote', 200000); UPDATE employees SET department_id = 6 WHERE employee_id = 7; SELECT first_name, department_id FROM employees WHERE employee_id = 7;",
    hints: [
      'INSERT INTO table VALUES (...); adds one row.',
      "UPDATE ... SET department_id = 6 WHERE employee_id = 7; changes the row. Don't forget WHERE!",
      'Finish with a SELECT to see the result — that is what gets validated.',
    ],
  },
  {
    id: 'advanced-30', level: 'advanced', db: 'company_db',
    title: 'Advanced SQL challenge',
    description: 'Put it all together.',
    objective: 'CTE + JOIN + aggregate + filter in one query.',
    instructions: 'Return the name and the number of employees (alias num_employees) of every department that has more employees than the overall average department size. Order by num_employees descending, then by name.',
    example: 'WITH sizes AS (SELECT department_id, COUNT(*) AS n FROM employees GROUP BY department_id) SELECT * FROM sizes WHERE n > 2;',
    starter: 'WITH dept_sizes AS (\n  SELECT department_id, COUNT(*) AS n\n  FROM employees\n  GROUP BY department_id\n)\n',
    solution: 'WITH dept_sizes AS (SELECT department_id, COUNT(*) AS n FROM employees GROUP BY department_id), stats AS (SELECT AVG(n) AS avg_n FROM dept_sizes) SELECT d.name, s.n AS num_employees FROM dept_sizes s JOIN departments d ON d.department_id = s.department_id, stats WHERE s.n > (SELECT avg_n FROM stats) ORDER BY num_employees DESC, d.name;',
    hints: [
      'First CTE: count employees per department.',
      'You need the average of those counts — a second CTE or subquery can compute it.',
      'Join the sizes back to departments for the name, filter with WHERE s.n > (average), then ORDER BY num_employees DESC, name.',
    ],
    ordered: true,
  }
];
