// Beginner challenges (1-10) — company_db.

export const beginner = [
  {
    id: 'beginner-1', level: 'beginner', db: 'company_db',
    title: 'SELECT basics',
    description: 'Retrieve everything from a table.',
    objective: 'Understand that SELECT * returns all columns and rows.',
    instructions: 'Write a query that returns every column and every row from the employees table.',
    example: 'SELECT * FROM departments;',
    starter: '-- Return all columns and rows from employees\nSELECT ',
    solution: 'SELECT * FROM employees;',
    hints: ['You need to retrieve information from the employees table.', 'The * symbol means "all columns".', 'Use: SELECT * FROM table_name;'],
  },
  {
    id: 'beginner-2', level: 'beginner', db: 'company_db',
    title: 'Selecting specific columns',
    description: 'Pick just the columns you need.',
    objective: 'Select a subset of columns by listing them after SELECT.',
    instructions: 'Return only the first_name and salary columns for every employee.',
    example: 'SELECT name FROM departments;',
    starter: 'SELECT ',
    solution: 'SELECT first_name, salary FROM employees;',
    hints: ['List the column names you want, separated by commas.', 'The FROM clause tells SQLite which table to read.', 'SELECT first_name, salary FROM employees;'],
  },
  {
    id: 'beginner-3', level: 'beginner', db: 'company_db',
    title: 'Filtering with WHERE',
    description: 'Return only rows matching a condition.',
    objective: 'Use WHERE to filter rows.',
    instructions: 'Find all employees who work in department 1 (Engineering). Return all columns.',
    example: "SELECT * FROM departments WHERE location = 'New York';",
    starter: 'SELECT * FROM employees\n',
    solution: 'SELECT * FROM employees WHERE department_id = 1;',
    hints: ['WHERE goes after FROM.', 'Compare the department_id column to 1.', 'SELECT * FROM employees WHERE department_id = 1;'],
  },
  {
    id: 'beginner-4', level: 'beginner', db: 'company_db',
    title: 'Sorting with ORDER BY',
    description: 'Order your results.',
    objective: 'Use ORDER BY with ASC/DESC.',
    instructions: 'Return first_name and salary of all employees, sorted by salary from highest to lowest.',
    example: 'SELECT name FROM departments ORDER BY name;',
    starter: 'SELECT first_name, salary\nFROM employees\n',
    solution: 'SELECT first_name, salary FROM employees ORDER BY salary DESC;',
    hints: ['ORDER BY decides the row order.', 'DESC means descending (largest first).', 'SELECT first_name, salary FROM employees ORDER BY salary DESC;'],
    ordered: true,
  },
  {
    id: 'beginner-5', level: 'beginner', db: 'company_db',
    title: 'Limiting results with LIMIT',
    description: 'Get only the top N rows.',
    objective: 'Use LIMIT to restrict how many rows are returned.',
    instructions: 'Return the last_name and hire_date of the 3 most recently hired employees (latest hire_date first).',
    example: 'SELECT name FROM departments LIMIT 2;',
    starter: 'SELECT last_name, hire_date\nFROM employees\n',
    solution: 'SELECT last_name, hire_date FROM employees ORDER BY hire_date DESC LIMIT 3;',
    hints: ['First sort by hire_date in descending order.', 'Then cut the list down with LIMIT.', 'SELECT last_name, hire_date FROM employees ORDER BY hire_date DESC LIMIT 3;'],
    ordered: true,
  },
  {
    id: 'beginner-6', level: 'beginner', db: 'company_db',
    title: 'Removing duplicates with DISTINCT',
    description: 'One of each value, please.',
    objective: 'Use DISTINCT to remove duplicate values.',
    instructions: 'Return each distinct department_id used in the employees table (one per row).',
    example: 'SELECT DISTINCT location FROM departments;',
    starter: 'SELECT DISTINCT ',
    solution: 'SELECT DISTINCT department_id FROM employees;',
    hints: ['DISTINCT goes immediately after SELECT.', 'You only need one column.', 'SELECT DISTINCT department_id FROM employees;'],
  },
  {
    id: 'beginner-7', level: 'beginner', db: 'company_db',
    title: 'Comparison operators',
    description: '<, >, <=, >=, =, !=',
    objective: 'Filter with numeric comparisons.',
    instructions: 'Find employees earning more than 60000. Return their first_name and salary.',
    example: 'SELECT * FROM projects WHERE budget > 100000;',
    starter: 'SELECT first_name, salary\nFROM employees\n',
    solution: 'SELECT first_name, salary FROM employees WHERE salary > 60000;',
    hints: ['The > operator compares numbers.', 'Put the condition in a WHERE clause.', 'SELECT first_name, salary FROM employees WHERE salary > 60000;'],
  },
  {
    id: 'beginner-8', level: 'beginner', db: 'company_db',
    title: 'AND / OR',
    description: 'Combine multiple conditions.',
    objective: 'Combine conditions with AND and OR.',
    instructions: 'Find employees in department 1 OR department 2 who earn more than 50000. Return first_name, department_id and salary.',
    example: 'SELECT * FROM employees WHERE salary > 60000 AND department_id = 1;',
    starter: 'SELECT first_name, department_id, salary\nFROM employees\nWHERE ',
    solution: 'SELECT first_name, department_id, salary FROM employees WHERE (department_id = 1 OR department_id = 2) AND salary > 50000;',
    hints: ['OR combines the two department options — put it in parentheses.', 'AND adds the salary condition on top.', 'WHERE (department_id = 1 OR department_id = 2) AND salary > 50000;'],
  },
  {
    id: 'beginner-9', level: 'beginner', db: 'company_db',
    title: 'Pattern matching with LIKE',
    description: 'Find text that matches a pattern.',
    objective: 'Use LIKE with % and _ wildcards.',
    instructions: "Find employees whose last_name starts with 'S'. Return first_name and last_name.",
    example: "SELECT * FROM employees WHERE first_name LIKE 'J%';",
    starter: "SELECT first_name, last_name\nFROM employees\nWHERE ",
    solution: "SELECT first_name, last_name FROM employees WHERE last_name LIKE 'S%';",
    hints: ['% matches any sequence of characters.', "'S%' means: starts with S, then anything.", "WHERE last_name LIKE 'S%';"],
  },
  {
    id: 'beginner-10', level: 'beginner', db: 'company_db',
    title: 'Ranges with BETWEEN',
    description: 'Filter values in a range.',
    objective: 'Use BETWEEN ... AND ... for inclusive ranges.',
    instructions: 'Find employees with a salary between 50000 and 70000 (inclusive). Return first_name and salary, sorted by salary.',
    example: 'SELECT * FROM projects WHERE budget BETWEEN 100000 AND 200000;',
    starter: 'SELECT first_name, salary\nFROM employees\n',
    solution: 'SELECT first_name, salary FROM employees WHERE salary BETWEEN 50000 AND 70000 ORDER BY salary;',
    hints: ['BETWEEN is inclusive on both ends.', 'Add ORDER BY at the very end.', 'WHERE salary BETWEEN 50000 AND 70000 ORDER BY salary;'],
    ordered: true,
  }
];
