// Debugging challenges ("Bug Hunt") — real-world broken queries to diagnose and fix.
// The starter query is always syntactically plausible but wrong; fix it so the
// result matches the expected output.

export const debug = [
  {
    id: 'debug-46', level: 'debug', db: 'company_db',
    title: 'Bug: the top-paid list looks wrong',
    description: 'A report shows the wrong people — fix the ranking.',
    objective: 'Debug ORDER BY direction and a missing LIMIT.',
    instructions: "This query was supposed to return the 3 highest-paid employees (highest first), but it returns everyone starting with the lowest paid. Fix it. Return first_name and salary.",
    example: 'SELECT name FROM employees ORDER BY hire_date ASC;',
    starter: '-- BUG: should show the top 3 earners, highest first\nSELECT first_name, salary\nFROM employees\nORDER BY salary ASC;',
    solution: 'SELECT first_name, salary FROM employees ORDER BY salary DESC LIMIT 3;',
    hints: ['ASC sorts from lowest to highest — the report needs the opposite.', 'To get only 3 rows, cut the list with LIMIT after ordering.', 'ORDER BY salary DESC LIMIT 3;'],
    ordered: true,
  },
  {
    id: 'debug-47', level: 'debug', db: 'company_db',
    title: 'Bug: the managers query returns nothing',
    description: "A classic: comparing with NULL using '='.",
    objective: 'Debug a NULL comparison that silently matches zero rows.',
    instructions: "This query should list employees who don't manage anyone (no manager), but it returns nothing. Return first_name and last_name.",
    example: "SELECT name FROM customers WHERE city = 'Boston';",
    starter: "-- BUG: returns no rows at all\nSELECT first_name, last_name\nFROM employees\nWHERE manager_id = NULL;",
    solution: "SELECT first_name, last_name FROM employees WHERE manager_id IS NULL;",
    hints: ["NULL means 'unknown' — it is never equal to anything, not even another NULL.", "To test for NULL you must use IS NULL (or IS NOT NULL).", 'WHERE manager_id IS NULL;'],
  },
  {
    id: 'debug-48', level: 'debug', db: 'school_db',
    title: 'Bug: the averages query throws an error',
    description: 'Aggregates need grouping — the engine says so.',
    objective: 'Debug a missing GROUP BY around an aggregate function.',
    instructions: 'This query should return each course title with the average of its enrollment grades, but it crashes with a "misuse of aggregate" error. Fix it. Return the course title and the average grade_value.',
    example: 'SELECT city, COUNT(*) FROM students GROUP BY city;',
    starter: '-- BUG: misuse of aggregate function error\nSELECT c.title, AVG(e.grade_value)\nFROM courses c\nJOIN enrollments e ON e.course_id = c.course_id;',
    solution: 'SELECT c.title, AVG(e.grade_value) FROM courses c JOIN enrollments e ON e.course_id = c.course_id GROUP BY c.title;',
    hints: ['Non-aggregated columns in the SELECT must appear in a GROUP BY clause.', 'GROUP BY goes after the JOIN / WHERE, before ORDER BY.', '...ON e.course_id = c.course_id GROUP BY c.title;'],
  },
  {
    id: 'debug-49', level: 'debug', db: 'shop_db',
    title: 'Bug: the inventory report lists sold-out items',
    description: 'The join answers the opposite of the question.',
    objective: 'Debug a JOIN that should have been an anti-join (NOT IN).',
    instructions: "This query was meant to list products that have NEVER been ordered, but it returns products that HAVE been ordered (some twice!). Fix it. Return only the product name.",
    example: 'SELECT name FROM customers WHERE customer_id NOT IN (SELECT customer_id FROM orders);',
    starter: '-- BUG: lists the opposite of what we want\nSELECT p.name\nFROM products p\nINNER JOIN order_items oi ON p.product_id = oi.product_id;',
    solution: 'SELECT p.name FROM products p WHERE p.product_id NOT IN (SELECT product_id FROM order_items);',
    hints: ['An INNER JOIN keeps products that DO appear in order_items — the opposite of what we need.', 'Keep products whose product_id is not in the set of ordered product ids.', 'SELECT name FROM products WHERE product_id NOT IN (SELECT product_id FROM order_items);'],
  },
  {
    id: 'debug-50', level: 'debug', db: 'library_db',
    title: "Bug: 'NULL' in quotes",
    description: 'Someone searched for a string, not a NULL.',
    objective: 'Debug a quoted-NULL comparison that filters everything out.',
    instructions: "This query should list the titles of books that are currently borrowed (their borrowing has no return date), but it returns an empty table. Fix it. Return the book title.",
    example: 'SELECT title FROM books WHERE year < 1950;',
    starter: "-- BUG: empty result, but the books table is fine\nSELECT b.title\nFROM books b\nINNER JOIN borrowings br ON b.book_id = br.book_id\nWHERE br.returned_on = 'NULL';",
    solution: 'SELECT b.title FROM books b INNER JOIN borrowings br ON b.book_id = br.book_id WHERE br.returned_on IS NULL;',
    hints: ["In SQL, 'NULL' in quotes is just a 4-letter string — it never matches the actual NULL value.", 'Missing return dates are stored as real NULLs; test them with IS NULL.', 'WHERE br.returned_on IS NULL;'],
  },
  {
    id: 'debug-51', level: 'debug', db: 'company_db',
    title: 'Bug: WHERE refuses to run an aggregate',
    description: 'Filtering groups needs HAVING, not WHERE.',
    objective: 'Debug a WHERE clause that illegally uses COUNT(*).',
    instructions: 'This query should list the department_id of every department with more than 3 employees, but it errors out. Fix it. Return department_id.',
    example: 'SELECT city, COUNT(*) FROM students GROUP BY city HAVING COUNT(*) > 1;',
    starter: '-- BUG: aggregates are not allowed in WHERE\nSELECT department_id\nFROM employees\nWHERE COUNT(*) > 3\nGROUP BY department_id;',
    solution: 'SELECT department_id FROM employees GROUP BY department_id HAVING COUNT(*) > 3;',
    hints: ['WHERE filters rows before grouping; it cannot use aggregate functions.', 'Conditions on grouped results belong in a HAVING clause, placed after GROUP BY.', 'GROUP BY department_id HAVING COUNT(*) > 3;'],
  },
];
