// Intermediate challenges (11-20) — company_db (aggregates & joins).

export const intermediate = [
  {
    id: 'intermediate-11', level: 'intermediate', db: 'company_db',
    title: 'Aggregate functions',
    description: 'SUM, AVG, MIN, MAX in one query.',
    objective: 'Compute summary statistics about a column.',
    instructions: 'Return one row with: the total salary (alias total), the average salary (alias average), and the highest salary (alias highest) of all employees.',
    example: 'SELECT MIN(budget), MAX(budget) FROM projects;',
    starter: 'SELECT ',
    solution: 'SELECT SUM(salary) AS total, AVG(salary) AS average, MAX(salary) AS highest FROM employees;',
    hints: ['Wrap salary in SUM(), AVG() and MAX().', 'Aliases are created with AS.', 'SELECT SUM(salary) AS total, AVG(salary) AS average, MAX(salary) AS highest FROM employees;'],
  },
  {
    id: 'intermediate-12', level: 'intermediate', db: 'company_db',
    title: 'COUNT',
    description: 'How many rows match?',
    objective: 'Use COUNT(*) and COUNT(column).',
    instructions: 'Count how many employees work in department 1.',
    example: 'SELECT COUNT(*) FROM projects;',
    starter: 'SELECT ',
    solution: 'SELECT COUNT(*) FROM employees WHERE department_id = 1;',
    hints: ['COUNT(*) counts rows.', 'Add the department filter in WHERE.', 'SELECT COUNT(*) FROM employees WHERE department_id = 1;'],
  },
  {
    id: 'intermediate-13', level: 'intermediate', db: 'company_db',
    title: 'SUM per group',
    description: 'Totals per category.',
    objective: 'Combine GROUP BY with SUM.',
    instructions: 'Return each department_id and the total salary of that department (alias total_salary), for every department.',
    example: 'SELECT department_id, SUM(budget) FROM projects GROUP BY department_id;',
    starter: 'SELECT department_id, ',
    solution: 'SELECT department_id, SUM(salary) AS total_salary FROM employees GROUP BY department_id;',
    hints: ['GROUP BY collects rows per department.', 'SUM(salary) then gives the per-group total.', 'SELECT department_id, SUM(salary) AS total_salary FROM employees GROUP BY department_id;'],
  },
  {
    id: 'intermediate-14', level: 'intermediate', db: 'company_db',
    title: 'AVG with rounding',
    description: 'Average per group.',
    objective: 'Use AVG and optionally ROUND.',
    instructions: 'Return each department_id with its average salary (alias avg_salary).',
    example: 'SELECT category, AVG(price) FROM products GROUP BY category;',
    starter: 'SELECT department_id, ',
    solution: 'SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id;',
    hints: ['AVG(salary) computes the mean.', 'Alias it with AS avg_salary.', 'SELECT department_id, AVG(salary) AS avg_salary FROM employees GROUP BY department_id;'],
  },
  {
    id: 'intermediate-15', level: 'intermediate', db: 'company_db',
    title: 'MIN and MAX',
    description: 'Extremes of a column.',
    objective: 'Use MIN and MAX.',
    instructions: 'Return the lowest and highest salary in the employees table as one row (aliases lowest, highest).',
    example: 'SELECT MIN(year), MAX(year) FROM books;',
    starter: 'SELECT ',
    solution: 'SELECT MIN(salary) AS lowest, MAX(salary) AS highest FROM employees;',
    hints: ['MIN() and MAX() each return one value.', 'SELECT MIN(salary) AS lowest, MAX(salary) AS highest FROM employees;'],
  },
  {
    id: 'intermediate-16', level: 'intermediate', db: 'company_db',
    title: 'GROUP BY counts',
    description: 'Count rows per group.',
    objective: 'Use GROUP BY with COUNT.',
    instructions: 'Return each department_id and how many employees work there (alias num_employees), sorted by num_employees descending.',
    example: 'SELECT genre, COUNT(*) FROM books GROUP BY genre;',
    starter: 'SELECT department_id, \nFROM employees\nGROUP BY department_id\n',
    solution: 'SELECT department_id, COUNT(*) AS num_employees FROM employees GROUP BY department_id ORDER BY num_employees DESC;',
    hints: ['COUNT(*) inside the SELECT gives per-group counts.', 'ORDER BY can use the alias num_employees.', 'SELECT department_id, COUNT(*) AS num_employees FROM employees GROUP BY department_id ORDER BY num_employees DESC;'],
    ordered: true,
  },
  {
    id: 'intermediate-17', level: 'intermediate', db: 'company_db',
    title: 'HAVING',
    description: 'Filter groups, not rows.',
    objective: 'Use HAVING to filter aggregated groups.',
    instructions: 'Return department_ids that have more than 2 employees, together with the employee count (alias num_employees).',
    example: 'SELECT genre, COUNT(*) FROM books GROUP BY genre HAVING COUNT(*) > 1;',
    starter: 'SELECT department_id, COUNT(*) AS num_employees\nFROM employees\nGROUP BY department_id\n',
    solution: 'SELECT department_id, COUNT(*) AS num_employees FROM employees GROUP BY department_id HAVING COUNT(*) > 2;',
    hints: ['HAVING filters after GROUP BY (WHERE filters before).', 'The condition is on COUNT(*).', 'HAVING COUNT(*) > 2;'],
  },
  {
    id: 'intermediate-18', level: 'intermediate', db: 'company_db',
    title: 'INNER JOIN',
    description: 'Combine two tables.',
    objective: 'Join employees to departments.',
    instructions: 'Return each employee first_name together with their department name. Join employees and departments on department_id.',
    example: 'SELECT p.name, d.name FROM projects p JOIN departments d ON p.department_id = d.department_id;',
    starter: 'SELECT e.first_name, d.name\nFROM employees e\n',
    solution: 'SELECT e.first_name, d.name FROM employees e INNER JOIN departments d ON e.department_id = d.department_id;',
    hints: ['Use table aliases: employees e, departments d.', 'Join condition: e.department_id = d.department_id.', 'SELECT e.first_name, d.name FROM employees e JOIN departments d ON e.department_id = d.department_id;'],
  },
  {
    id: 'intermediate-19', level: 'intermediate', db: 'company_db',
    title: 'LEFT JOIN',
    description: 'Keep rows without a match.',
    objective: 'Use LEFT JOIN and understand NULLs.',
    instructions: 'Return every project name together with its department name — including projects that somehow have no matching department. Use a LEFT JOIN from projects to departments.',
    example: 'SELECT c.name, o.order_id FROM customers c LEFT JOIN orders o ON c.customer_id = o.customer_id;',
    starter: 'SELECT p.name, d.name\nFROM projects p\n',
    solution: 'SELECT p.name, d.name FROM projects p LEFT JOIN departments d ON p.department_id = d.department_id;',
    hints: ['LEFT JOIN keeps all rows of the left table.', 'The join key is department_id.', 'SELECT p.name, d.name FROM projects p LEFT JOIN departments d ON p.department_id = d.department_id;'],
  },
  {
    id: 'intermediate-20', level: 'intermediate', db: 'company_db',
    title: 'Multiple-table query',
    description: 'Three tables at once.',
    objective: 'Join three tables and aggregate.',
    instructions: 'Return each department name and the total budget of its projects (alias total_budget). Join projects to departments; include departments even with no projects (LEFT JOIN from departments).',
    example: 'SELECT s.name, COUNT(e.enrollment_id) FROM students s LEFT JOIN enrollments e ON s.student_id = e.student_id GROUP BY s.name;',
    starter: 'SELECT d.name, \nFROM departments d\n',
    solution: 'SELECT d.name, SUM(p.budget) AS total_budget FROM departments d LEFT JOIN projects p ON d.department_id = p.department_id GROUP BY d.name;',
    hints: ['Start from departments and LEFT JOIN projects.', 'SUM(p.budget) totals the project budgets per department.', "SELECT d.name, SUM(p.budget) AS total_budget FROM departments d LEFT JOIN projects p ON d.department_id = p.department_id GROUP BY d.name;"],
  }
];
