// library_db challenges — authors, books, members, borrowings.

export const library = [
  {
    id: 'library-1', level: 'beginner', db: 'library_db',
    title: 'Newest books first',
    description: 'Sort books by publication year.',
    objective: 'Use ORDER BY with DESC.',
    instructions: 'Return the title and year of every book, sorted from newest to oldest.',
    example: 'SELECT title, year FROM books ORDER BY year;',
    starter: 'SELECT title, year\nFROM books\n',
    solution: 'SELECT title, year FROM books ORDER BY year DESC;',
    hints: ['ORDER BY decides the row order.', 'DESC means descending (largest / newest first).', 'SELECT title, year FROM books ORDER BY year DESC;'],
    ordered: true,
  },
  {
    id: 'library-2', level: 'beginner', db: 'library_db',
    title: 'Unreturned borrowings',
    description: 'Find NULL values with IS NULL.',
    objective: 'Filter for missing values.',
    instructions: 'Return the borrow_id of every borrowing that has not been returned yet (returned_on is NULL).',
    example: 'SELECT borrow_id FROM borrowings WHERE returned_on IS NOT NULL;',
    starter: 'SELECT borrow_id\nFROM borrowings\n',
    solution: 'SELECT borrow_id FROM borrowings WHERE returned_on IS NULL;',
    hints: ['You cannot use = with NULL.', 'IS NULL matches rows where the column is empty.', 'SELECT borrow_id FROM borrowings WHERE returned_on IS NULL;'],
  },
  {
    id: 'library-3', level: 'intermediate', db: 'library_db',
    title: 'Borrowings per member',
    description: 'Count activity per member.',
    objective: 'Join two tables and count per group.',
    instructions: 'Return each member name with the number of borrowings they have made.',
    example: 'SELECT m.name, COUNT(*) FROM members m JOIN borrowings br ON m.member_id = br.member_id GROUP BY m.name;',
    starter: 'SELECT m.name, COUNT(*)\nFROM members m\nJOIN borrowings br ON m.member_id = br.member_id\n',
    solution: 'SELECT m.name, COUNT(*) FROM members m JOIN borrowings br ON m.member_id = br.member_id GROUP BY m.name;',
    hints: ['Join members to borrowings on member_id.', 'COUNT(*) counts rows per group.', 'Add GROUP BY m.name to get one row per member.'],
  },
  {
    id: 'library-4', level: 'intermediate', db: 'library_db',
    title: 'Currently borrowed books',
    description: 'Books that are still out.',
    objective: 'Join tables and filter on NULL.',
    instructions: 'Return the title of every book whose borrowing has not been returned yet (returned_on is NULL).',
    example: 'SELECT b.title FROM borrowings br JOIN books b ON br.book_id = b.book_id WHERE br.returned_on IS NULL;',
    starter: 'SELECT b.title\nFROM borrowings br\nJOIN books b ON br.book_id = b.book_id\n',
    solution: 'SELECT b.title FROM borrowings br JOIN books b ON br.book_id = b.book_id WHERE br.returned_on IS NULL;',
    hints: ['Join borrowings to books on book_id.', 'Filter with WHERE returned_on IS NULL on the borrowings alias.', 'SELECT b.title FROM borrowings br JOIN books b ON br.book_id = b.book_id WHERE br.returned_on IS NULL;'],
  },
  {
    id: 'library-5', level: 'advanced', db: 'library_db',
    title: 'Fans of UK authors',
    description: 'Members who borrowed a UK book.',
    objective: 'Nest multiple subqueries.',
    instructions: "Return the name of every member who has borrowed at least one book written by an author from the 'UK'. Each name should appear once.",
    example: "SELECT name FROM members WHERE member_id IN (SELECT member_id FROM borrowings WHERE book_id IN (SELECT book_id FROM books WHERE genre = 'Satire'));",
    starter: "SELECT name\nFROM members\nWHERE \n",
    solution: "SELECT DISTINCT name FROM members WHERE member_id IN (SELECT member_id FROM borrowings WHERE book_id IN (SELECT book_id FROM books WHERE author_id IN (SELECT author_id FROM authors WHERE country = 'UK')));",
    hints: ['Start from the innermost question: which authors are from the UK?', 'Then find their books, then the borrowings, then the members.', "WHERE member_id IN (SELECT member_id FROM borrowings WHERE book_id IN (SELECT book_id FROM books WHERE author_id IN (SELECT author_id FROM authors WHERE country = 'UK'))) and add DISTINCT."],
  },
];
