// school_db challenges — students, teachers, courses, enrollments.

export const school = [
  {
    id: 'school-1', level: 'beginner', db: 'school_db',
    title: 'Filtering students by city',
    description: 'Find students from a specific city.',
    objective: 'Use WHERE on a text column.',
    instructions: "Return the name and city of every student from 'Boston'.",
    example: "SELECT name, city FROM students WHERE city = 'Chicago';",
    starter: "SELECT name, city\nFROM students\n",
    solution: "SELECT name, city FROM students WHERE city = 'Boston';",
    hints: ['Filter with a WHERE clause on the city column.', "Text values need single quotes: 'Boston'.", "SELECT name, city FROM students WHERE city = 'Boston';"],
  },
  {
    id: 'school-2', level: 'beginner', db: 'school_db',
    title: 'Sorting students alphabetically',
    description: 'Order results by a text column.',
    objective: 'Use ORDER BY on a TEXT column.',
    instructions: 'Return the name of every student in grade 11, sorted alphabetically by name (A first).',
    example: 'SELECT name FROM students ORDER BY name;',
    starter: 'SELECT name\nFROM students\n',
    solution: 'SELECT name FROM students WHERE grade = 11 ORDER BY name;',
    hints: ['WHERE grade = 11 keeps only grade-11 students.', 'ASC is the default sort direction, so plain ORDER BY name works.', 'SELECT name FROM students WHERE grade = 11 ORDER BY name;'],
    ordered: true,
  },
  {
    id: 'school-3', level: 'intermediate', db: 'school_db',
    title: 'Average grade per course',
    description: 'Aggregate enrollment grades.',
    objective: 'Join two tables and use AVG with GROUP BY.',
    instructions: 'Return each course title with the average grade_value across its enrollments, rounded to 1 decimal place. Order of rows does not matter.',
    example: 'SELECT p.category, ROUND(AVG(p.price), 1) FROM products p GROUP BY p.category;',
    starter: 'SELECT c.title, ROUND(AVG(e.grade_value), 1)\nFROM enrollments e\nJOIN courses c ON e.course_id = c.course_id\n',
    solution: 'SELECT c.title, ROUND(AVG(e.grade_value), 1) FROM enrollments e JOIN courses c ON e.course_id = c.course_id GROUP BY c.title;',
    hints: ['Join enrollments to courses on course_id.', 'AVG(grade_value) grouped by course title.', 'SELECT c.title, ROUND(AVG(e.grade_value), 1) FROM enrollments e JOIN courses c ON e.course_id = c.course_id GROUP BY c.title;'],
  },
  {
    id: 'school-4', level: 'intermediate', db: 'school_db',
    title: 'Filtering groups with HAVING',
    description: 'Find students enrolled in many courses.',
    objective: 'Use GROUP BY with a HAVING clause.',
    instructions: 'Return each student_id and the number of enrollments for students who are enrolled in more than 2 courses.',
    example: 'SELECT customer_id, COUNT(*) FROM orders GROUP BY customer_id HAVING COUNT(*) > 2;',
    starter: 'SELECT student_id, COUNT(*)\nFROM enrollments\nGROUP BY student_id\n',
    solution: 'SELECT student_id, COUNT(*) FROM enrollments GROUP BY student_id HAVING COUNT(*) > 2;',
    hints: ['Group the enrollments by student_id first.', 'HAVING filters groups, WHERE filters rows.', 'SELECT student_id, COUNT(*) FROM enrollments GROUP BY student_id HAVING COUNT(*) > 2;'],
  },
  {
    id: 'school-5', level: 'advanced', db: 'school_db',
    title: 'High achievers',
    description: 'Students with an outstanding grade.',
    objective: 'Use IN with a subquery.',
    instructions: 'Find the name of every student who has at least one enrollment with a grade_value above 90. Return each name once.',
    example: 'SELECT name FROM customers WHERE customer_id IN (SELECT customer_id FROM orders WHERE status = \'shipped\');',
    starter: 'SELECT name\nFROM students\nWHERE \n',
    solution: 'SELECT DISTINCT name FROM students WHERE student_id IN (SELECT student_id FROM enrollments WHERE grade_value > 90);',
    hints: ['Use IN with a subquery on the enrollments table.', 'The subquery selects student_id where grade_value > 90.', 'WHERE student_id IN (SELECT student_id FROM enrollments WHERE grade_value > 90) and add DISTINCT.'],
  },
];
