// shop_db challenges — customers, products, orders, order_items.

export const shop = [
  {
    id: 'shop-1', level: 'beginner', db: 'shop_db',
    title: 'Priced above 100',
    description: 'Filter products by price.',
    objective: 'Use a numeric comparison in WHERE.',
    instructions: 'Return the name and price of every product that costs more than 100.',
    example: 'SELECT name, price FROM products WHERE price < 10;',
    starter: 'SELECT name, price\nFROM products\n',
    solution: 'SELECT name, price FROM products WHERE price > 100;',
    hints: ['The > operator compares numbers.', 'Put the condition in a WHERE clause on the price column.', 'SELECT name, price FROM products WHERE price > 100;'],
  },
  {
    id: 'shop-2', level: 'beginner', db: 'shop_db',
    title: 'Customers from a city',
    description: 'Filter customers by city.',
    objective: 'Use WHERE on a text column.',
    instructions: "Return the name of every customer from 'New York'.",
    example: "SELECT name FROM customers WHERE city = 'Boston';",
    starter: "SELECT name\nFROM customers\n",
    solution: "SELECT name FROM customers WHERE city = 'New York';",
    hints: ["Text values need single quotes: 'New York'.", 'Filter on the city column.', "SELECT name FROM customers WHERE city = 'New York';"],
  },
  {
    id: 'shop-3', level: 'intermediate', db: 'shop_db',
    title: 'Units sold per product',
    description: 'Total quantity ordered for each product.',
    objective: 'Use SUM with GROUP BY.',
    instructions: 'Return each product_id with the total quantity of that product across all order_items.',
    example: 'SELECT product_id, SUM(quantity) FROM order_items GROUP BY product_id;',
    starter: 'SELECT product_id, SUM(quantity)\nFROM order_items\n',
    solution: 'SELECT product_id, SUM(quantity) FROM order_items GROUP BY product_id;',
    hints: ['SUM adds up the quantity values.', 'GROUP BY product_id makes one total per product.', 'SELECT product_id, SUM(quantity) FROM order_items GROUP BY product_id;'],
  },
  {
    id: 'shop-4', level: 'intermediate', db: 'shop_db',
    title: 'Cancelled orders',
    description: 'Who cancelled an order?',
    objective: 'Join two tables and filter with WHERE.',
    instructions: "Return the name of every customer who has at least one order with status 'cancelled'. Each name should appear once.",
    example: "SELECT name FROM customers c JOIN orders o ON c.customer_id = o.customer_id WHERE o.status = 'pending';",
    starter: "SELECT name\nFROM customers c\nJOIN orders o ON c.customer_id = o.customer_id\n",
    solution: "SELECT DISTINCT name FROM customers c JOIN orders o ON c.customer_id = o.customer_id WHERE o.status = 'cancelled';",
    hints: ['Join customers to orders on customer_id.', "Filter with WHERE o.status = 'cancelled'.", 'Add DISTINCT so repeated names collapse to one row.', "SELECT DISTINCT name FROM customers c JOIN orders o ON c.customer_id = o.customer_id WHERE o.status = 'cancelled';"],
  },
  {
    id: 'shop-5', level: 'advanced', db: 'shop_db',
    title: 'Order totals',
    description: 'How much is each order worth?',
    objective: 'Join order_items to products and aggregate a computed column.',
    instructions: 'Return each order_id with its total value (SUM of quantity * price for its items). Order of rows does not matter.',
    example: 'SELECT o.order_id, SUM(oi.quantity * p.price) FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY o.order_id;',
    starter: 'SELECT oi.order_id, SUM(oi.quantity * p.price)\nFROM order_items oi\nJOIN products p ON oi.product_id = p.product_id\n',
    solution: 'SELECT oi.order_id, SUM(oi.quantity * p.price) FROM order_items oi JOIN products p ON oi.product_id = p.product_id GROUP BY oi.order_id;',
    hints: ['Multiply quantity by price for each item.', 'Join order_items to products on product_id to get the price.', 'GROUP BY oi.order_id gives one total per order.'],
  },
];
