// Interactive SQL Cheat Sheet content.
// Each entry: syntax, explanation, example, mistakes[], whenToUse.

export const CHEATSHEET = [
  { id: 'select', cat: 'Basics', name: 'SELECT',
    syntax: 'SELECT column1, column2\nFROM table_name;',
    explanation: 'Reads data from a table. List the columns you want, or use * for all of them.',
    example: 'SELECT first_name, salary\nFROM employees;',
    mistakes: ['Missing FROM clause.', 'Misspelling column names — check the Database panel.'],
    when: 'Whenever you need to look at data.' },
  { id: 'where', cat: 'Basics', name: 'WHERE',
    syntax: 'SELECT *\nFROM employees\nWHERE salary > 50000;',
    explanation: 'Filters rows — only rows where the condition is true are returned.',
    example: "SELECT * FROM employees\nWHERE department_id = 1 AND salary > 50000;",
    mistakes: ["Using = NULL instead of IS NULL.", "Using == instead of =."],
    when: 'To narrow down results to matching rows.' },
  { id: 'distinct', cat: 'Basics', name: 'DISTINCT',
    syntax: 'SELECT DISTINCT column\nFROM table_name;',
    explanation: 'Returns each distinct value only once.',
    example: 'SELECT DISTINCT department_id\nFROM employees;',
    mistakes: ['Expecting it to apply per single column when multiple columns are listed — it applies to the whole row.'],
    when: 'To see the unique values of a column.' },
  { id: 'orderby', cat: 'Basics', name: 'ORDER BY',
    syntax: 'SELECT *\nFROM employees\nORDER BY salary DESC;',
    explanation: 'Sorts result rows. ASC = ascending (default), DESC = descending. Multiple keys allowed, comma separated.',
    example: 'SELECT first_name, salary FROM employees\nORDER BY department_id ASC, salary DESC;',
    mistakes: ['Writing ORDER salary BY.', 'Sorting text when you meant to sort numbers.'],
    when: 'Whenever row order matters (top-N, reports).' },
  { id: 'limit', cat: 'Basics', name: 'LIMIT',
    syntax: 'SELECT *\nFROM employees\nORDER BY salary DESC\nLIMIT 5;',
    explanation: 'Restricts the number of returned rows. Often combined with ORDER BY for "top N".',
    example: 'SELECT name FROM projects LIMIT 3;',
    mistakes: ['LIMIT after the wrong clause — it must be last.'],
    when: 'Previewing data or getting top-N lists.' },
  { id: 'like', cat: 'Filtering', name: 'LIKE',
    syntax: "SELECT *\nFROM employees\nWHERE last_name LIKE 'S%';",
    explanation: 'Pattern matching on text. % = any characters, _ = exactly one character.',
    example: "SELECT * FROM employees\nWHERE email LIKE '%@corp.com';",
    mistakes: ['LIKE is case-insensitive in SQLite for ASCII, but case-sensitive in many other databases.', 'Forgetting quotes around the pattern.'],
    when: 'Searching text that partially matches.' },
  { id: 'in', cat: 'Filtering', name: 'IN',
    syntax: "SELECT *\nFROM employees\nWHERE department_id IN (1, 3, 5);",
    explanation: 'Matches a value against a list (or a subquery) — shorthand for many ORs.',
    example: "SELECT * FROM projects\nWHERE status IN ('active', 'planned');",
    mistakes: ['Mixing types: IN (\'1\', 2).'],
    when: 'Testing membership in a known set.' },
  { id: 'between', cat: 'Filtering', name: 'BETWEEN',
    syntax: 'SELECT *\nFROM employees\nWHERE salary BETWEEN 50000 AND 70000;',
    explanation: 'Inclusive range check — same as salary >= 50000 AND salary <= 70000.',
    example: 'SELECT * FROM projects\nWHERE budget BETWEEN 100000 AND 300000;',
    mistakes: ['Assuming the end value is excluded — it is included.'],
    when: 'Numeric or date ranges.' },
  { id: 'andor', cat: 'Filtering', name: 'AND / OR',
    syntax: 'SELECT *\nFROM employees\nWHERE department_id = 1\n  AND (salary > 50000 OR manager_id IS NOT NULL);',
    explanation: 'Combines conditions. AND needs both sides true; OR needs at least one. Use parentheses to control precedence.',
    example: 'SELECT * FROM employees\nWHERE salary > 60000 AND department_id = 2;',
    mistakes: ['Mixing AND/OR without parentheses — AND binds tighter than OR.'],
    when: 'Any multi-condition filter.' },
  { id: 'count', cat: 'Aggregates', name: 'COUNT',
    syntax: 'SELECT COUNT(*)\nFROM employees;',
    explanation: 'Counts rows. COUNT(*) counts all rows; COUNT(column) skips NULLs.',
    example: 'SELECT COUNT(*) AS num_employees\nFROM employees\nWHERE department_id = 1;',
    mistakes: ['Using COUNT(column) when rows have NULLs and you wanted all rows.'],
    when: '"How many...?" questions.' },
  { id: 'sum', cat: 'Aggregates', name: 'SUM',
    syntax: 'SELECT SUM(salary)\nFROM employees;',
    explanation: 'Adds up a numeric column.',
    example: 'SELECT SUM(budget) AS total_budget\nFROM projects;',
    mistakes: ['SUM on text columns — convert or fix the data first.'],
    when: 'Totals per table or per group.' },
  { id: 'avg', cat: 'Aggregates', name: 'AVG',
    syntax: 'SELECT AVG(salary)\nFROM employees;',
    explanation: 'Arithmetic mean of a numeric column (NULLs ignored).',
    example: 'SELECT ROUND(AVG(salary), 2) AS avg_salary\nFROM employees;',
    mistakes: ['Forgetting that AVG ignores NULL rows entirely.'],
    when: 'Averages and benchmarks.' },
  { id: 'minmax', cat: 'Aggregates', name: 'MIN / MAX',
    syntax: 'SELECT MIN(salary), MAX(salary)\nFROM employees;',
    explanation: 'Smallest / largest value of a column. Works on numbers, text and dates.',
    example: 'SELECT MIN(hire_date) AS first_hire,\n       MAX(hire_date) AS last_hire\nFROM employees;',
    mistakes: ['MIN/MAX of a text column returns alphabetical extremes, which may surprise you.'],
    when: 'Extremes and date ranges.' },
  { id: 'groupby', cat: 'Aggregates', name: 'GROUP BY',
    syntax: 'SELECT department_id, COUNT(*)\nFROM employees\nGROUP BY department_id;',
    explanation: 'Groups rows sharing a value so aggregates run per group.',
    example: 'SELECT department_id, AVG(salary) AS avg_salary\nFROM employees\nGROUP BY department_id;',
    mistakes: ['Selecting a non-aggregated column that is not in GROUP BY.', 'Using WHERE to filter groups instead of HAVING.'],
    when: 'Per-category summaries.' },
  { id: 'having', cat: 'Aggregates', name: 'HAVING',
    syntax: 'SELECT department_id, COUNT(*)\nFROM employees\nGROUP BY department_id\nHAVING COUNT(*) > 2;',
    explanation: 'Filters groups after aggregation. WHERE filters rows before grouping.',
    example: 'SELECT department_id, SUM(salary) AS total\nFROM employees\nGROUP BY department_id\nHAVING SUM(salary) > 100000;',
    mistakes: ['Using column aliases inside HAVING.'],
    when: 'Conditions on aggregates (COUNT, SUM, ...).' },
  { id: 'innerjoin', cat: 'Joins', name: 'INNER JOIN',
    syntax: 'SELECT e.first_name, d.name\nFROM employees e\nINNER JOIN departments d\n  ON e.department_id = d.department_id;',
    explanation: 'Combines rows of two tables where the join condition matches. Non-matching rows are dropped.',
    example: 'SELECT p.name, d.name AS department\nFROM projects p\nJOIN departments d ON p.department_id = d.department_id;',
    mistakes: ['Forgetting ON — you get every row × every row.', 'Ambiguous column names without table prefixes.'],
    when: 'When you only want matching pairs.' },
  { id: 'leftjoin', cat: 'Joins', name: 'LEFT JOIN',
    syntax: 'SELECT c.name, o.order_id\nFROM customers c\nLEFT JOIN orders o\n  ON c.customer_id = o.customer_id;',
    explanation: 'Keeps ALL rows of the left table; missing right-side values become NULL.',
    example: 'SELECT d.name, COUNT(p.project_id) AS num_projects\nFROM departments d\nLEFT JOIN projects p ON d.department_id = p.department_id\nGROUP BY d.name;',
    mistakes: ['Putting a left-table filter in the ON clause (use WHERE).', 'Using COUNT(*) instead of COUNT(right.column) — counts 1 instead of 0 for non-matches.'],
    when: '"Show all X, even without Y" questions.' },
  { id: 'rightjoin', cat: 'Joins', name: 'RIGHT JOIN',
    syntax: 'SELECT e.first_name, d.name\nFROM employees e\nRIGHT JOIN departments d\n  ON e.department_id = d.department_id;',
    explanation: 'Keeps all rows of the right table. SQLite supports RIGHT JOIN since version 3.39 — otherwise swap the tables and use LEFT JOIN.',
    example: 'SELECT d.name, e.first_name\nFROM employees e\nRIGHT JOIN departments d\n  ON e.department_id = d.department_id;',
    mistakes: ['Relying on RIGHT JOIN in older SQLite versions.'],
    when: 'When the "keep everything" table is on the right (or just rewrite as LEFT JOIN).' },
  { id: 'union', cat: 'Sets', name: 'UNION',
    syntax: 'SELECT first_name AS person\nFROM employees\nUNION\nSELECT name FROM departments;',
    explanation: 'Combines two result sets with the same number of columns. UNION removes duplicates; UNION ALL keeps them (faster).',
    example: 'SELECT city FROM customers\nUNION\nSELECT location FROM departments;',
    mistakes: ['Different column counts in the two SELECTs.', 'Using UNION when you actually want duplicates (UNION ALL).'],
    when: 'Merging similar lists.' },
  { id: 'case', cat: 'Logic', name: 'CASE',
    syntax: "SELECT name,\n  CASE WHEN salary >= 70000 THEN 'High'\n       ELSE 'Standard' END AS band\nFROM employees;",
    explanation: 'Inline if/else logic. Conditions are checked top to bottom; ELSE is the fallback.',
    example: "SELECT name,\n  CASE WHEN stock = 0 THEN 'out'\n       WHEN stock < 20 THEN 'low'\n       ELSE 'ok' END AS status\nFROM products;",
    mistakes: ['Missing END or ELSE.', 'Conditions are evaluated in order — put the most specific first.'],
    when: 'Categorizing or transforming values in the result.' },
  { id: 'subqueries', cat: 'Logic', name: 'Subqueries',
    syntax: 'SELECT first_name\nFROM employees\nWHERE salary > (SELECT AVG(salary) FROM employees);',
    explanation: 'A query inside another query. Can appear in WHERE, FROM, or SELECT.',
    example: "SELECT name FROM customers\nWHERE customer_id IN\n  (SELECT customer_id FROM orders WHERE status = 'shipped');",
    mistakes: ['Correlated subqueries run per row and can be slow.', 'Forgetting parentheses around the inner query.'],
    when: 'Comparisons against computed values.' },
  { id: 'cte', cat: 'Logic', name: 'CTE (WITH)',
    syntax: 'WITH dept_avg AS (\n  SELECT department_id, AVG(salary) AS avg_salary\n  FROM employees\n  GROUP BY department_id\n)\nSELECT * FROM dept_avg;',
    explanation: 'A named temporary result that makes complex queries readable. Multiple CTEs are comma-separated.',
    example: 'WITH big_projects AS (\n  SELECT * FROM projects WHERE budget > 150000\n)\nSELECT name FROM big_projects;',
    mistakes: ['Defining a CTE but never selecting from it.', 'A semicolon before the main query terminates it early.'],
    when: 'Multi-step logic; readable replacement for nested subqueries.' },
  { id: 'window', cat: 'Logic', name: 'Window functions',
    syntax: 'SELECT first_name,\n  RANK() OVER (ORDER BY salary DESC) AS rnk\nFROM employees;',
    explanation: 'Aggregate/ranking values computed across rows without collapsing them. PARTITION BY restarts per group.',
    example: 'SELECT first_name, department_id,\n  AVG(salary) OVER (PARTITION BY department_id) AS dept_avg\nFROM employees;',
    mistakes: ['Every window function needs OVER().', 'RANK vs ROW_NUMBER: RANK gives ties the same rank.'],
    when: 'Rankings, running totals, per-group comparisons on row level.' },
  { id: 'insert', cat: 'Modify', name: 'INSERT',
    syntax: "INSERT INTO departments\nVALUES (6, 'Legal', 'Remote', 200000);",
    explanation: 'Adds new rows. You can also list columns explicitly.',
    example: "INSERT INTO employees (first_name, last_name, department_id)\nVALUES ('Ana', 'Lopez', 1);",
    mistakes: ['Wrong column order with positional VALUES.', 'Violating NOT NULL / PRIMARY KEY constraints.'],
    when: 'Adding data.' },
  { id: 'update', cat: 'Modify', name: 'UPDATE',
    syntax: 'UPDATE employees\nSET salary = salary * 1.1\nWHERE employee_id = 3;',
    explanation: 'Changes values in existing rows.',
    example: "UPDATE products SET price = price * 0.9\nWHERE category = 'Electronics';",
    mistakes: ['Forgetting WHERE — updates EVERY row. Always test with SELECT first.'],
    when: 'Fixing or bulk-changing data.' },
  { id: 'delete', cat: 'Modify', name: 'DELETE',
    syntax: 'DELETE FROM employees\nWHERE employee_id = 12;',
    explanation: 'Removes rows that match the condition.',
    example: 'DELETE FROM order_items\nWHERE quantity = 0;',
    mistakes: ['DELETE FROM table without WHERE removes all rows!'],
    when: 'Removing data.' },
  { id: 'create', cat: 'Schema', name: 'CREATE TABLE',
    syntax: 'CREATE TABLE departments (\n  department_id INTEGER PRIMARY KEY,\n  name TEXT NOT NULL,\n  budget INTEGER\n);',
    explanation: 'Defines a new table with its columns, types and constraints.',
    example: 'CREATE TABLE tags (\n  tag_id INTEGER PRIMARY KEY,\n  label TEXT UNIQUE\n);',
    mistakes: ['Missing commas between columns.', 'SQLite accepts almost any column type — be deliberate.'],
    when: 'Defining your own schema.' },
  { id: 'alter', cat: 'Schema', name: 'ALTER TABLE',
    syntax: 'ALTER TABLE employees\nADD COLUMN phone TEXT;',
    explanation: 'Changes an existing table: add/rename columns, rename the table.',
    example: 'ALTER TABLE employees RENAME COLUMN phone TO contact;',
    mistakes: ['Older SQLite versions cannot drop columns directly.'],
    when: 'Evolving a schema without recreating it.' },
  { id: 'drop', cat: 'Schema', name: 'DROP TABLE',
    syntax: 'DROP TABLE departments;',
    explanation: 'Deletes the table and all of its data permanently.',
    example: 'DROP TABLE IF EXISTS temp_results;',
    mistakes: ['No undo — use the Reset Database button if you drop something by accident.'],
    when: 'Cleanup. Careful!' }
];
